# Generated by Django 4.2 on 2023-05-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='barcode',
            field=models.CharField(default=1, max_length=15, verbose_name='Bar Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='photo',
            field=models.ImageField(default=1, upload_to='sold_products/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'brand')},
        ),
    ]
