# Generated by Django 4.2 on 2023-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_soldproduct_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='barcode',
            field=models.CharField(max_length=15, verbose_name='Bar Code'),
        ),
        migrations.AlterUniqueTogether(
            name='soldproduct',
            unique_together={('barcode', 'product')},
        ),
    ]
