# Generated by Django 4.2 on 2023-06-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0006_soldproduct_city_alter_brand_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("thermex", "Thermex"), ("other", "Other")],
                default="thermex",
                max_length=60,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="products/%Y/%m", verbose_name="Photo"),
        ),
        migrations.AddField(
            model_name="product",
            name="sell_point",
            field=models.PositiveIntegerField(default=100, verbose_name="Sell Point"),
        ),
        migrations.CreateModel(
            name="UserBoughtProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bought_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "UserBoughtProducts",
                "verbose_name_plural": "UserBoughtProducts",
            },
        ),
    ]
