# Generated by Django 4.2 on 2023-06-06 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0001_initial"),
        ("products", "0007_category_type_product_photo_product_sell_point_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBoughtProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "prize_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.prizeproduct",
                        verbose_name="Prize Product",
                    ),
                ),
                (
                    "thermex_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Thermex Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bought_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "UserBoughtProducts",
                "verbose_name_plural": "UserBoughtProducts",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="type",
        ),
        migrations.DeleteModel(
            name="UserBoughtProducts",
        ),
    ]
