# Generated by Django 4.2 on 2023-06-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_userboughtproduct_prize_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soldproduct",
            name="barcode",
            field=models.CharField(max_length=14, verbose_name="Bar Code"),
        ),
    ]
