version: '3'
services:
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "80:8000"