# Generated by Django 4.2 on 2023-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(choices=[('tashkent', 'Tashkent'), ('samarkand', 'Samarkand'), ('bukhara', 'Bukhara'), ('khiva', 'Khiva'), ('fergana', 'Fergana'), ('namangan', 'Namangan'), ('andijan', 'Andijan'), ('navoi', 'Navoi'), ('nukus', 'Nukus'), ('termez', 'Termez'), ('urgench', 'Urgench'), ('kokand', 'Kokand')], max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
    ]
