# Generated by Django 4.2 on 2023-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.CharField(choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Khiva', 'Khiva'), ('Fergana', 'Fergana'), ('Namangan', 'Namangan'), ('Andijan', 'Andijan'), ('Navoi', 'Navoi'), ('Nukus', 'Nukus'), ('Termez', 'Termez'), ('Urgench', 'Urgench'), ('Kokand', 'Kokand'), ('Jizzakh', 'Jizzakh'), ('Qarshi', 'Qarshi'), ('Margilan', 'Margilan')], max_length=255),
        ),
    ]
