# Generated by Django 4.2 on 2023-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupation",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="occupation",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="occupation",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Name"),
        ),
    ]
