# Generated by Django 4.2 on 2023-05-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_region_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.CharField(choices=[('Tashkent shahri', 'Tashkent shahri'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Andijon', 'Andijon'), ('Fergana', 'Fergana'), ('Jizzakh', 'Jizzakh'), ('Namangan', 'Namangan'), ('Navoi', 'Navoi'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpogiston', 'Qoraqalpogiston'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Xorazm', 'Xorazm')], max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
