# Generated by Django 4.2 on 2023-05-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_notification_text_ru_notification_text_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
