# Generated by Django 4.2 on 2023-05-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('Akfachi', 'Akfachi'), ('Santexnik', 'Santexnik'), ('Dokonchi', 'Dokonchi')], default='Santexnik', max_length=255),
        ),
    ]
