# Generated by Django 4.2 on 2023-05-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='First Name'),
            preserve_default=False,
        ),
    ]
