# Generated by Django 4.2 on 2023-05-03 19:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=32, null=True, region=None, unique=True, verbose_name='Phone number')),
                ('code', models.CharField(blank=True, help_text='This field is created automatically', max_length=10)),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires In')),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Code',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=32, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
