# Generated by Django 4.2 on 2023-05-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users/%Y/%m", verbose_name="Photo"),
        ),
    ]
