# Generated by Django 4.2 on 2023-05-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('Sotuvchi', 'Sotuvchi'), ('Chilangar', 'Chilangar')], default='Chilangar', max_length=255),
        ),
    ]
