# Generated by Django 4.2 on 2023-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.PositiveIntegerField(default=0, verbose_name="Points"),
        ),
    ]
