# Generated by Django 4.2 on 2023-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=13, unique=True, verbose_name="Phone number"
            ),
        ),
    ]
