# Generated by Django 4.2 on 2023-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="phone",
            field=models.CharField(max_length=13, null=True, verbose_name="Phone number"),
        ),
    ]
