# Generated by Django 4.2 on 2023-06-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prizechildcategory",
            name="name_ru",
            field=models.CharField(max_length=256, null=True, verbose_name="PrizeChildCategory"),
        ),
        migrations.AddField(
            model_name="prizechildcategory",
            name="name_uz",
            field=models.CharField(max_length=256, null=True, verbose_name="PrizeChildCategory"),
        ),
        migrations.AddField(
            model_name="prizeparentcategory",
            name="name_ru",
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="prizeparentcategory",
            name="name_uz",
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name="Name"),
        ),
    ]
