# Generated by Django 4.2 on 2023-06-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_prizeproduct_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prizechildcategory",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="prize/child_category/%Y/%m",
                verbose_name="Photo",
            ),
        ),
        migrations.AddField(
            model_name="prizeparentcategory",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="prize/parent_category/%Y/%m",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="prizeproduct",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="prize/products/%Y/%m",
                verbose_name="Photo",
            ),
        ),
    ]
