from django.db import models
from django.utils.translation import gettext_lazy as _


class City(models.TextChoices):
    TashkentShahri = "Tashkent shahri", _("Tashkent shahri")
    ToshkentViloyati = "Toshkent viloyati", _("Toshkent viloyati")
    Samarkand = "Samarkand", _("Samarkand")
    Bukhara = "Bukhara", _("Bukhara")
    Andijon = "Andijon", _("Andijon")
    Fergana = "Fergana", _("Fergana")
    Jizzakh = "Jizzakh", _("Jizzakh")
    Namangan = "Namangan", _("Namangan")
    Navoi = "Navoi", _("Navoi")
    Qashqadaryo = "Qashqadaryo", _("Qashqadaryo")
    Qoraqalpogiston = "Qoraqalpogiston", _("Qoraqalpogiston")
    Sirdaryo = "Sirdaryo", _("Sirdaryo")
    Surxondaryo = "Surxondaryo", _("Surxondaryo")
    Xorazm = "Xorazm", _("Xorazm")


class Job(models.TextChoices):
    Sotuvchi = "Sotuvchi", _("Sotuvchi")
    Chilangar = "Chilangar", _("Chilangar")


REGION_CHOICES = {
    "Tashkent shahri": [
        "Bektemir tumani",
        "Chilonzor tumani",
        "Mirobod tumani",
        "Mirzo Ulugbek tumani",
        "Olmazor tumani",
        "Sergeli tumani",
        "Shayhontohur tumani",
        "Uchtepa tumani",
        "Yakkasaroy tumani",
        "Yashnaobod tumani",
        "Yunusobod tumani",
    ],
    "Toshkent viloyati": [
        "Angren shahri",
        "Bekobod shahri",
        "Bekobod tumani",
        "Boka tumani",
        "Bo'stonliq tumani",
        "Chinoz tumani",
        "Chirchiq shahri",
        "O'rta chirchiq tumani",
        "Ohangaron tumani",
        "Olmaliq shahri",
        "Oqqo'rg'on tumani",
        "Parkent tumani",
        "Piskent tumani",
        "Qibray tumani",
        "Quyi chirchiq tumani",
        "Yangiyo'l tumani",
        "Yuqori chirchiq tumani",
        "Zangiota tumani",
    ],
    "Samarkand": [
        "Bulung'ur tumani",
        "Ishtixon tumani",
        "Jomboy tumani",
        "Kattaqo'rg'on shahri",
        "Kattaqo'rg'on tumani",
        "Narpay tumani",
        "Nurobod tumani",
        "Oqdaryo tumani",
        "Past darg'om tumani",
        "Paxtachi tumani",
        "Poyariq tumani",
        "Qo'shrabot tumani",
        "Samarqand shahri",
        "Samarqand tumani",
        "Toyloq tumani",
        "Urgut tumani",
    ],
    "Bukhara": [
        "Buxoro shahri",
        "Buhoro tumani",
        "G'ijduvon tumani",
        "Jondor tumani",
        "Kogon tumani",
        "Olot tumani",
        "Peshko tumani",
        "Qorako'l tumani",
        "Qorovulbozor tumani",
        "Romiton tumani",
        "Shofirkon tumani",
        "Vobkent tumani",
    ],
    "Andijon": [
        "Andijon shahri",
        "Andijon tumani",
        "Asaka tumani",
        "Baliqchi tumani",
        "Bo'ston tumani",
        "Buloqboshi tumani",
        "Izboskan tumani",
        "Jalaquduq tumani",
        "Marhamat tumani",
        "Oltinko'l tumani",
        "Pahtaobod tumani",
        "Qo'rgo'ntepa tumani",
        "Shahrixon tumani",
        "Ulug'nor tumani",
        "Xo'jaobod tumani",
        "Xonobod shahri",
    ],
    "Fergana": [
        "Beshariq tumani",
        "Bog'dod tumani",
        "Buvayda tumani",
        "Dang'ara tumani",
        "Farg'ona shahri",
        "Farg'ona tumani",
        "Furqat tumani",
        "Marg'ilon shahri",
        "O'zbekiston tumani",
        "Oltiariq tumani",
        "Qo'qon shahri",
        "Qo'shtepa tumani",
        "Quva tumani",
        "Quvasoy shahri",
        "Rishton tumani",
        "So'x tumani",
        "Toshloq tumani",
        "Uchko'prik tumani",
        "Yozyovon tumani",
    ],
    "Jizzakh": [
        "Arnasoy tumani",
        "Baxmal tumani",
        "Do'stlik tumani",
        "Forish tumani",
        "G'allaorol tumani",
        "Jizzax shahri",
        "Jizzax tumani",
        "Mirzacho'l tumani",
        "Paxtakor tumani",
        "Yangiobod tumani",
        "Zafarobod tumani",
        "Zarband tumani",
        "Zomin tumani",
    ],
    "Namangan": [
        "Namangan shahri",
        "Namangan tumani",
        "Chortoq tumani",
        "Chust tumani",
        "Kosonsoy tumani",
        "Mingbuloq tumani",
        "Norin tumani",
        "Pop tumani",
        "To'raqo'rg'on tumani",
        "Uchqo'rg'on tumani",
        "Uychi tumani",
        "Yangiqo'rgon tumani",
    ],
    "Navoi": [
        "Karmana tumani",
        "Konimex tumani",
        "Navbahor tumani",
        "Navoiy shahri",
        "Nurota tumani",
        "Qiziltepa tumani",
        "Tomdi tumani",
        "Uchquduq tumani",
        "Xatirchi tumani",
        "Zarafshon shahri",
    ],
    "Qashqadaryo": [
        "Chiroqchi tumani",
        "Dehqonobod tumani",
        "G'uzor tumani",
        "Kasbi tumani",
        "Kitob tumani",
        "Koson tuman",
        "Mirishkor tumani",
        "Muborak tumani",
        "Nishon tumani",
        "Qamashi tumani",
        "Qarshi shahri",
        "Qarshi tumani",
        "Shahrisabz shahri",
        "Yakkabog' tumani",
    ],
    "Qoraqalpogiston": [
        "Amudaryo tumani",
        "Beruniy tumani",
        "Chimboy tumani",
        "Ellikqala tumani",
        "Kegeyli tumani",
        "Mo'ynoq tumani",
        "Nukus shahri",
        "Nukus tumani",
        "Qonliko'l tumani",
        "Qorauzaq tumani",
        "Qung'irot tumani",
        "Shumanay tumani",
        "Taxiatosh shahri",
        "Taxtako'pir tumani",
        "To'rtko'l tumani",
        "Xo'jayli tumani",
    ],
    "Sirdaryo": [
        "Boyovut tumani",
        "Guliston shahri",
        "Guliston tumani",
        "Oqoltin tumani",
        "Sardoba tumani",
        "Sayxunobod tumani",
        "Shirin shahri",
        "Sirdaryo tumani",
        "Xovos tumani",
        "Yangiyer shahri",
    ],
    "Surxondaryo": [
        "Angor tumani",
        "Bandixon tumani",
        "Boysun tumani",
        "Denov tumani",
        "Jarqo'rg'on tumani",
        "Muzrobot tumani",
        "Oltinsoy tumani",
        "Qiziriq tumani",
        "Qumqo'rg'on tumani",
        "Sariosiyo tumani",
        "Sherobod tumani",
        "Sho'rchi tumani",
        "Termiz shahri",
        "Termiz tumani",
        "Uzun tumani",
    ],
    "Xorazm": [
        "Bog'ot tumani",
        "Gurlan tumani",
        "Qo'shko'pir tumani",
        "Shovot tumani",
        "Urganch shahri",
        "Urganch tumani",
        "Xazorasp tumani",
        "Xiva tumani",
        "Xonqa tumani",
        "Yangiariq tumani",
        "Yangibozor tumani",
    ],
}
cities_translations = {
    "Tashkent shahri": {
        "Bektemir tumani": "Бектемирский район",
        "Chilonzor tumani": "Чиланзарский район",
        "Mirobod tumani": "Мирабадский район",
        "Mirzo Ulugbek tumani": "Мирзо-Улугбекский район",
        "Olmazor tumani": "Юнусабадский район",
        "Sergeli tumani": "Сергелийский район",
        "Shayhontohur tumani": "Шайхантахурский район",
        "Uchtepa tumani": "Учтепинский район",
        "Yakkasaroy tumani": "Яккасарайский район",
        "Yashnaobod tumani": "Яшнабадский район",
        "Yunusobod tumani": "Юнусабадский район",
    },
    "Toshkent viloyati": {
        "Angren shahri": "город Ангрен",
        "Bekobod shahri": "город Бекабад",
        "Bekobod tumani": "Бекабадский район",
        "Boka tumani": "Бухарский район",
        "Bo'stonliq tumani": "Бостанлыкский район",
        "Chinoz tumani": "Чиназский район",
        "Chirchiq shahri": "город Чирчик",
        "O'rta chirchiq tumani": "Ортачирчикский район",
        "Ohangaron tumani": "Ахангаранский район",
        "Olmaliq shahri": "город Алмалык",
        "Oqqo'rg'on tumani": "Аккурганский район",
        "Parkent tumani": "Паркентский район",
        "Piskent tumani": "Пискентский район",
        "Qibray tumani": "Кибрайский район",
        "Quyi chirchiq tumani": "Куйичирчикский район",
        "Yangiyo'l tumani": "Янгиюльский район",
        "Yuqori chirchiq tumani": "Юкоричирчикский район",
        "Zangiota tumani": "Зангиатинский район",
    },
    "Samarkand": {
        "Bulung'ur tumani": "Булунгурский район",
        "Ishtixon tumani": "Иштиханский район",
        "Jomboy tumani": "Джамбайский район",
        "Kattaqo'rg'on shahri": "Город Каттакурган",
        "Kattaqo'rg'on tumani": "Каттакурганский район",
        "Narpay tumani": "Нарпайский район",
        "Nurobod tumani": "Нурободский район",
        "Oqdaryo tumani": "Акдарьинский район",
        "Past darg'om tumani": "Пастдаргомский район",
        "Paxtachi tumani": "Пахтачийский район",
        "Poyariq tumani": "Паярикский район",
        "Qo'shrabot tumani": "Кошрабадский район",
        "Samarqand shahri": "Город Самарканд",
        "Samarqand tumani": "Самаркандский район",
        "Toyloq tumani": "Тойлокский район",
        "Urgut tumani": "Ургутский район",
    },
    "Bukhara": {
        "Buxoro shahri": "Город Бухара",
        "Buhoro tumani": "Бухарский район",
        "G'ijduvon tumani": "Гиждувонский район",
        "Jondor tumani": "Жондорский район",
        "Kogon tumani": "Когонский район",
        "Olot tumani": "Алатский район",
        "Peshko tumani": "Пешкунский район",
        "Qorako'l tumani": "Каракульский район",
        "Qorovulbozor tumani": "Карабулакский район",
        "Romiton tumani": "Ромитанский район",
        "Shofirkon tumani": "Шофирканский район",
        "Vobkent tumani": "Вобкентский район",
    },
    "Andijon": {
        "Andijon shahri": "Город Андижан",
        "Andijon tumani": "Андижанский район",
        "Asaka tumani": "Асакинский район",
        "Baliqchi tumani": "Балыкчинский район",
        "Bo'ston tumani": "Бостанский район",
        "Buloqboshi tumani": "Булакбашинский район",
        "Izboskan tumani": "Избасканский район",
        "Jalaquduq tumani": "Джалалкудукский район",
        "Marhamat tumani": "Мархаматский район",
        "Oltinko'l tumani": "Алтынкульский район",
        "Pahtaobod tumani": "Пахтаабадский район",
        "Qo'rgo'ntepa tumani": "Кургантепинский район",
        "Shahrixon tumani": "Шахрихонский район",
        "Ulug'nor tumani": "Улугнорский район",
        "Xo'jaobod tumani": "Ходжаабадский район",
        "Xonobod shahri": "Город Ханабад",
    },
    "Fergana": {
        "Beshariq tumani": "Бешарыкский район",
        "Bog'dod tumani": "Багатский район",
        "Buvayda tumani": "Бувайдинский район",
        "Dang'ara tumani": "Дангаринский район",
        "Farg'ona shahri": "Город Фергана",
        "Farg'ona tumani": "Ферганский район",
        "Furqat tumani": "Фуркатский район",
        "Marg'ilon shahri": "Город Маргилан",
        "O'zbekiston tumani": "Узбекистанский район",
        "Oltiariq tumani": "Алтыарыкский район",
        "Qo'qon shahri": "Город Коканд",
        "Qo'shtepa tumani": "Куштепинский район",
        "Quva tumani": "Кувинский район",
        "Quvasoy shahri": "Город Кувасай",
        "Rishton tumani": "Риштанский район",
        "So'x tumani": "Сохский район",
        "Toshloq tumani": "Ташлакский район",
        "Uchko'prik tumani": "Учкуприкский район",
        "Yozyovon tumani": "Йозёвонский район",
    },
    "Jizzakh": {
        "Arnasoy tumani": "Арнасайский район",
        "Baxmal tumani": "Бахмальский район",
        "Do'stlik tumani": "Дустликский район",
        "Forish tumani": "Фаришский район",
        "G'allaorol tumani": "Галляаральский район",
        "Jizzax shahri": "Город Джизак",
        "Jizzax tumani": "Джизакский район",
        "Mirzachul tumani": "Мирзачульский район",
        "Paxtakor tumani": "Пахтакорский район",
        "Yangiobod tumani": "Янгиабадский район",
        "Zafarobod tumani": "Зафарабадский район",
        "Zarbdor tumani": "Зарбдорский район",
        "Zomin tumani": "Зоминский район",
    },
    "Namangan": {
        "Namangan shahri": "город Наманган",
        "Namangan tumani": "Наманганский район",
        "Chortoq tumani": "Чартакский район",
        "Chust tumani": "Чустский район",
        "Kosonsoy tumani": "Касансайский район",
        "Mingbuloq tumani": "Мингбулакский район",
        "Norin tumani": "Нарынский район",
        "Pop tumani": "Папский район",
        "To'raqo'rg'on tumani": "Тошкентский район",
        "Uchqo'rg'on tumani": "Учкурганский район",
        "Uychi tumani": "Уйчинский район",
        "Yangiqo'rgon tumani": "Янгикурганский район",
    },
    "Navoi": {
        "Karmana tumani": "Кармана райони",
        "Konimex tumani": "Қонимех райони",
        "Navbahor tumani": "Навбаҳор райони",
        "Navoiy shahri": "Навоий шаҳри",
        "Nurota tumani": "Нурота райони",
        "Qiziltepa tumani": "Қизилтепа райони",
        "Tomdi tumani": "Томди райони",
        "Uchquduq tumani": "Учқудуқ райони",
        "Xatirchi tumani": "Хатирчи райони",
        "Zarafshon shahri": "Зарафшон шаҳри",
    },
    "Qashqadaryo": {
        "Chiroqchi tumani": "Чирокчи район",
        "Dehqonobod tumani": "Дехконабадский район",
        "G'uzor tumani": "Гузарский район",
        "Kasbi tumani": "Каршийский район",
        "Kitob tumani": "Китабский район",
        "Koson tuman": "Касанский район",
        "Mirishkor tumani": "Миришкорский район",
        "Muborak tumani": "Мубарекский район",
        "Nishon tumani": "Нишанский район",
        "Qamashi tumani": "Камашийский район",
        "Qarshi shahri": "Город Карши",
        "Qarshi tumani": "Каршинский район",
        "Shahrisabz shahri": "Город Шахрисабз",
        "Yakkabog' tumani": "Яккабагский район",
    },
    "Qoraqalpogiston": {
        "Amudaryo tumani": "Амударьинский район",
        "Beruniy tumani": "Берунийский район",
        "Chimboy tumani": "Чимбойский район",
        "Ellikqala tumani": "Элликкалинский район",
        "Kegeyli tumani": "Кегейлийский район",
        "Mo'ynoq tumani": "Муйнакский район",
        "Nukus shahri": "г. Нукус",
        "Nukus tumani": "Нукусский район",
        "Qonliko'l tumani": "Канлыкульский район",
        "Qorauzaq tumani": "Каракалпакский район",
        "Qung'irot tumani": "Кунградский район",
        "Shumanay tumani": "Шуманайский район",
        "Taxiatosh shahri": "г. Тахиаташ",
        "Taxtako'pir tumani": "Тахтакупырский район",
        "To'rtko'l tumani": "Турткульский район",
        "Xo'jayli tumani": "Ходжейлийский район",
    },
    "Sirdaryo": {
        "Boyovut tumani": "Байавутский район",
        "Guliston shahri": "Ходжейлийский район",
        "Guliston tumani": "Ходжейлийский район",
        "Oqoltin tumani": "Аккурганский район",
        "Sardoba tumani": "Сардобинский район",
        "Sayxunobod tumani": "Сайхунабадский район",
        "Shirin shahri": "Сирдарьинский район",
        "Sirdaryo tumani": "Сирдарьинский район",
        "Xovos tumani": "Хавастский район",
        "Yangiyer shahri": "Янгиерский район",
    },
    "Surxondaryo": {
        "Angor tumani": "Ангорский район",
        "Bandixon tumani": "Бандиханский район",
        "Boysun tumani": "Байсунский район",
        "Denov tumani": "Денауский район",
        "Jarqo'rg'on tumani": "Яркурганский район",
        "Muzrobot tumani": "Музрабатский район",
        "Oltinsoy tumani": "Олтинсойский район",
        "Qiziriq tumani": "Кизирикский район",
        "Qumqo'rg'on tumani": "Кумкурганский район",
        "Sariosiyo tumani": "Сариасийский район",
        "Sherobod tumani": "Шерабадский район",
        "Sho'rchi tumani": "Шурчинский район",
        "Termiz shahri": "Город Термез",
        "Termiz tumani": "Термезский район",
        "Uzun tumani": "Узунский район",
    },
    "Xorazm": {
        "Bog'ot tumani": "Боготский район",
        "Gurlan tumani": "Гурленский район",
        "Qo'shko'pir tumani": "Кара-Калпакский район",
        "Shovot tumani": "Шаватский район",
        "Urganch shahri": "город Ургенч",
        "Urganch tumani": "Ургенчский район",
        "Xazorasp tumani": "Хазараспский район",
        "Xiva tumani": "Хивинский район",
        "Xonqa tumani": "Ханкинский район",
        "Yangiariq tumani": "Янгиарыкский район",
        "Yangibozor tumani": "Янгибазарский район",
    },
}


regions_translations = {
    "Tashkent shahri": "Ташкент",
    "Toshkent viloyati": "Ташкентская область",
    "Samarkand": "Самаркандская область",
    "Bukhara": "Бухарская область",
    "Andijon": "Андижанская область",
    "Fergana": "Ферганская область",
    "Jizzakh": "Джизакская область",
    "Namangan": "Наманганская область",
    "Navoi": "Навоийская область",
    "Qashqadaryo": "Кашкадарьинская область",
    "Qoraqalpogiston": "Республика Каракалпакстан",
    "Sirdaryo": "Сырдарьинская область",
    "Surxondaryo": "Сурхандарьинская область",
    "Xorazm": "Хорезмская область",
}


category_choices = ["Water Heaters", "Boilers"]
category_choices_translations = {"Boilers": "Котлы", "Water Heaters": "Водонагреватели"}
category_brand_dict = {
    "Water Heaters": ["GIRO", "SILVERHEAT", "NOVA", "Nobel", "Thermo", "TITANIUMHEAT", "GARANTERM"],
    "Boilers": ["Mizudo", "ETALON"],
}

brand_product_dict = {
    "GIRO": ["GIRO 50 V/H", "GIRO 80 V/H", "GIRO 100 V/H"],
    "SILVERHEAT": [
        "ECO FLAT 30V",
        "ERS 50 V SILVERHEAT",
        "ERS 80 V SILVERHEAT",
        "ERS 100 V SILVERHEAT",
        "ERS 150 V SILVERHEAT",
        "ESS 30 V Slim SILVERHEAT",
        "ESS 50 V Slim SILVERHEAT",
        "ESS 50 H Slim SILVERHEAT",
        "ESS 80 V Slim SILVERHEAT",
    ],
    "NOVA": [
        "NOVA 50 V",
        "NOVA 80 V",
        "NOVA 100 V",
    ],
    "Nobel": [
        "Nobel 10 0",
        "Nobel 10 U",
        "Nobel 15 O",
        "Nobel 15 U",
    ],
    "Thermo": [
        "THERMO 30 V Slim",
        "THERMO 50 V Slim",
        "THERMO 80 V",
        "THERMO 100 V",
        "THERMO 150 V",
    ],
    "TITANIUMHEAT": [
        "TITANIUMHEAT 50 V",
        "TITANIUMHEAT 80 V",
        "TITANIUMHEAT 80 H ",
        "TITANIUMHEAT 100 V",
        "TITANIUMHEAT 150 V",
        "TITANIUMHEAT ES 30 V",
        "TITANIUMHEAT ES 50 H Slim ",
        "TITANIUMHEAT ES 50 V Slim",
    ],
    "GARANTERM": [
        "ECO 50V",
        "ECO 80V",
        "ECO 100V",
        "ORIGIN 50 V",
        "ORIGIN 80 V",
        "ORIGIN 80H (rop)",
        "ORIGIN 100V",
        "ORIGIN 150 V",
        "ORIGIN SLIM 30 V",
        "ORIGIN SLIM 50 H",
        "ORIGIN SLIM 50 V",
        "ORIGIN SLIM 65 V",
        "ORIGIN SLIM 80 V",
    ],
    "Mizudo": [
        "M 15 T MIZUDO",
        "M 17T MIZUDO",
        "M 24 T MIZUDO",
        "M 36 T MIZUDO",
        "M 40 T MIZUDO",
    ],
    "ETALON": [
        "ER 50 V ETALON",
        "ER 80 V ETALON",
        "ER 100 V ETALON",
        "ER 150 V ETALON",
        "ES 30 V ETALON Slim",
        "ES 50 V ETALON Slim",
    ],
}
