name: CI/CD
run-name: ${{ github.actor }} is testing the thermex.uz 🚀
on:
  push:
jobs:
  testing:
      runs-on: ubuntu-latest
      container: python:3.9

      services:
        db:
          image: postgres
          env:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: sammy
            POSTGRES_DB: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/dev.txt') }}
        - name: Install dependencies
          run: pip install -r requirements/dev.txt
        - name: Install gettext
          run: apt-get update && apt-get install -y gettext
        - name: Create env file
          run: |
            echo "${{ secrets.ENV_FILE }}" >> .env
        - name: Compile messages
          run: python3 manage.py compilemessages
        - name: Run Tests
          run: python3 manage.py test
        - name: Run Linter
          run: make lint

  deploy:
    runs-on: ubuntu-latest
    needs: testing
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Create .pem file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > my.pem
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copy docker-compose.yml to EC2 instance
        run: |
            chmod 600 my.pem
            ssh -o StrictHostKeyChecking=no -i my.pem ec2-user@$18.228.10.255 "mkdir -p ~/docker-compose"
      - name: Job Status
        run: echo "🍏 Deployment status is ${{ job.status }}."